source "https://rubygems.org"

ruby "3.2.3"

gem "rails", "~> 7.1.0"
gem "pg"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

group :development, :test do
  gem 'pry'
  gem 'rails-controller-testing'
end

gem 'faraday'
gem 'rspec-rails', '~> 6.0'

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end
